---
- name: 'Create S3 bucket.'
  amazon.aws.s3_bucket:
    aws_access_key: "{{ aws_default_access_key_id }}"
    aws_secret_key: "{{ aws_default_secret_access_key }}"
    region: "{{ aws_region }}"
    name: "{{ k8s_s3_bucket_name }}"
    state: 'present'
    versioning: no
