---
- name: 'Create or update IAM policy for cluster.'
  delegate_to: 'localhost'
  community.aws.iam_policy:
    aws_access_key: "{{ aws_default_access_key_id }}"
    aws_secret_key: "{{ aws_default_secret_access_key }}"
    region: "{{ aws_region }}"
    iam_type: 'user'
    iam_name: "{{ k8s_aws_iam_cluster_user }}"
    policy_name: "{{ k8s_aws_iam_cluster_user }}_policy"
    state: 'present'
    skip_duplicates: no
    policy_json: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "SsmPolicyStatement",
            "Effect": "Allow",
            "Action": [
              "ssm:GetParameterHistory",
              "ssm:GetParametersByPath",
              "ssm:GetParameters",
              "ssm:GetParameter",
              "ssm:PutParameter"
            ],
            "Resource": "arn:aws:ssm:*:{{ aws_account_id }}:parameter/{{ k8s_aws_ssm_policy_pattern }}"
          },
          {
            "Sid": "S3BucketPolicyStatement",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
              "arn:aws:s3:::{{ k8s_s3_bucket_name }}",
              "arn:aws:s3:::{{ k8s_s3_bucket_name }}/*"
            ]
          }
        ]
      }
