---
- name: 'Add External-Secrets chart repository.'
  kubernetes.core.helm_repository:
    name: 'external-secrets'
    repo_url: 'https://external-secrets.github.io/kubernetes-external-secrets/'

- name: 'Deploy External-Secrets.'
  kubernetes.core.helm:
    name: 'external-secrets'
    chart_ref: 'external-secrets/kubernetes-external-secrets'
    release_namespace: 'external-secrets'
    create_namespace: yes
    values:
      envVarsFromSecret.aws_default_access_key_id: "{{ k8s_access_key_id }}"
      envVarsFromSecret.aws_default_secret_access_key: "{{ k8s_secret_access_key }}"
      env.POLLER_INTERVAL_MILLISECONDS: 3600000
      env.AWS_REGION: "{{ aws_region }}"
