---
- name: 'Create or update IAM SSM policy for cluster.'
  delegate_to: 'localhost'
  community.aws.iam_policy:
    aws_access_key: "{{ k8s_aws_main_access_key }}"
    aws_secret_key: "{{ k8s_aws_main_secret_key }}"
    region: "{{ k8s_aws_region }}"
    iam_type: 'user'
    iam_name: "{{ k8s_aws_iam_cluster_user }}"
    policy_name: "{{ k8s_aws_iam_cluster_user }}_policy"
    state: 'present'
    skip_duplicates: no
    policy_json: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "SsmPolicyStatement",
            "Effect": "Allow",
            "Action": [
              "ssm:GetParameterHistory",
              "ssm:GetParametersByPath",
              "ssm:GetParameters",
              "ssm:GetParameter",
              "ssm:PutParameter"
            ],
            "Resource": "arn:aws:ssm:*:{{ k8s_aws_account_id }}:parameter/{{ k8s_aws_ssm_policy_pattern }}"
          }
        ]
      }
