---
- name: 'Add Jetstack chart repository.'
  kubernetes.core.helm_repository:
    name: 'jetstack'
    repo_url: 'https://charts.jetstack.io/'

- name: 'Deploy Cert-Manager.'
  kubernetes.core.helm:
    name: 'cert-manager'
    chart_ref: 'jetstack/cert-manager'
    release_namespace: 'cert-manager'
    create_namespace: yes
    values:
      installCRDs: true

- name: 'Create Route 53 secret access key secret.'
  kubernetes.core.k8s:
    kubeconfig: '~/.kube/config'
    namespace: 'cert-manager'
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      type: 'Opaque'
      metadata:
        name: 'route53-secret-key'
        namespace: "cert-manager"
      data:
        key: "{{ k8s_aws_main_secret_key | b64encode }}"

- name: 'Deploy Issuer.'
  kubernetes.core.k8s:
    kubeconfig: '~/.kube/config'
    namespace: 'cert-manager'
    definition:
      apiVersion: 'cert-manager.io/v1'
      kind: 'ClusterIssuer'
      metadata:
        name: 'letsencrypt-prod'
      spec:
        acme:
          email: "letsencrypt@{{ k8s_private_domain_name }}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          privateKeySecretRef:
            name: 'letsencrypt-prod-private-key'
          solvers:
          - selector:
              dnsZones:
                - "{{ k8s_personal_fqdn }}"
            dns01:
              route53:
                region: "{{ k8s_aws_region }}"
                hostedZoneID: "{{ k8s_route53_personal_zone_id }}"
                accessKeyID: "{{ k8s_aws_main_access_key }}"
                secretAccessKeySecretRef:
                  name: 'route53-secret-key'
                  key: 'key'
          - selector:
              dnsZones:
                - "{{ k8s_private_fqdn }}"
            dns01:
              route53:
                region: "{{ k8s_aws_region}}"
                hostedZoneID: "{{ k8s_route53_private_zone_id }}"
                accessKeyID: "{{ k8s_aws_main_access_key }}"
                secretAccessKeySecretRef:
                  name: 'route53-secret-key'
                  key: 'key'
