---
- name: 'Set fact for the NFS server IP address.'
  ansible.builtin.set_fact:
    k8s_nfs_server_ip_address: "{{ hostvars[k8s_nfs_server].pve_ip_address }}"

- name: 'Add nfs-subdir-external-provisioner chart repository.'
  kubernetes.core.helm_repository:
    name: 'nfs-subdir-external-provisioner'
    repo_url: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'

- name: 'Deploy nfs-subdir-external-provisioner.'
  kubernetes.core.helm:
    name: 'nfs-subdir-external-provisioner'
    chart_ref: 'nfs-subdir-external-provisioner/nfs-subdir-external-provisioner'
    release_namespace: 'nfs-client'
    create_namespace: yes
    values:
      nfs:
        server: "{{ k8s_nfs_server_ip_address }}"
        path: "{{ k8s_nfs_prefix }}/{{ k8s_cluster }}"
        volumeName: "nfs-root-{{ k8s_cluster }}"
      storageClass:
        create: yes
        provisionerName: "{{ k8s_cluster }}-nfs-provisioner"
        defaultClass: yes
        name: 'nfs-client'
        allowVolumeExpansion: yes
        reclaimPolicy: 'Delete'
        archiveOnDelete: yes
        accessModes: 'ReadWriteMany'
