---
- name: 'Create DNS records.'
  delegate_to: 'localhost'
  block:

    - name: "Create privately-resolvable DNS records for the cluster."
      community.aws.route53:
        overwrite: yes
        aws_access_key: "{{ k8s_aws_main_access_key }}"
        aws_secret_key: "{{ k8s_aws_main_secret_key }}"
        hosted_zone_id: "{{ k8s_route53_private_zone_id }}"
        state: 'present'
        type: 'A'
        record: "{{ k8s_route53_private_fqdn }}"
        value: "{{ k8s_ipv4_address }}"

    - name: "Create privately-resolvable wildcard DNS records for the cluster."
      community.aws.route53:
        alias: yes
        alias_hosted_zone_id: "{{ k8s_route53_private_zone_id }}"
        overwrite: yes
        aws_access_key: "{{ k8s_aws_main_access_key }}"
        aws_secret_key: "{{ k8s_aws_main_secret_key }}"
        hosted_zone_id: "{{ k8s_route53_private_zone_id }}"
        state: 'present'
        type: 'A'
        record: "*.{{ k8s_route53_private_fqdn }}"
        value: "{{ k8s_route53_private_fqdn }}"

    - name: "Create publicly-resolvable DNS records for the cluster."
      community.aws.route53:
        alias: yes
        alias_hosted_zone_id: "{{ k8s_route53_personal_zone_id }}"
        overwrite: yes
        aws_access_key: "{{ k8s_aws_main_access_key }}"
        aws_secret_key: "{{ k8s_aws_main_secret_key }}"
        hosted_zone_id: "{{ k8s_route53_personal_zone_id }}"
        state: 'present'
        type: 'A'
        record: "{{ k8s_route53_personal_fqdn }}"
        value: "{{ k8s_personal_domain_name }}"

    - name: "Create publicly-resolvable wildcard DNS records for the cluster."
      community.aws.route53:
        alias: yes
        alias_hosted_zone_id: "{{ k8s_route53_personal_zone_id }}"
        overwrite: yes
        aws_access_key: "{{ k8s_aws_main_access_key }}"
        aws_secret_key: "{{ k8s_aws_main_secret_key }}"
        hosted_zone_id: "{{ k8s_route53_personal_zone_id }}"
        state: 'present'
        type: 'A'
        record: "*.{{ k8s_route53_personal_fqdn }}"
        value: "{{ k8s_route53_personal_fqdn }}"
