---
# The root path shared with Traefik for its configuration.
traefik_data_dir: '/traefik'

# Account ID, access key, etc used to create policies, users, Route 53 records, etc.
aws_region: 'us-east-1'
aws_account_id: null
route53_access_key_id: null
route53_secret_access_key: null

# A private domain name.
private_domain_name: 'example.net'

# Clean, simple hostname.
clean_hostname: "{{ clean_hostname | splitext | first | lower }}"

# Local timezone.
local_timezone: 'America/New_York'

# A "private" FQDN.
host_private_fqdn: "torrents.{{ private_domain_name }}"

# A Route 53 "private" zone ID.
route53_private_zone_id: null

# LetsEncrypt private domain resolver name.
letsencrypt_private_domain_resolver: "{{ private_domain_name | splitext | first }}"
# LetsEncrypt email address.
letsencrypt_email_address: "letsencrypt@{{ private_domain_name }}"

# The root directory for torrent data.
torrent_data_path: '/torrents'

# The base port.
transmission_base_port: 60000

# The user.
normal_user_name: 'nathan'

# The group.
normal_user_group: 'users'

# The UID.
normal_user_uid: '1000'

# The GID.
normal_user_gid: '1000'

# The actual instances (an array of objects).
torrent_client_instances: []
# Don't reuse IDs!
# - id: 3
#   name: debian

# Announcement URL domain -> tracker name map.
torrent_domains_announce_map: {}
# fun-times.debian.org: 'debian'
