---
- name: 'Setup APT.'
  ansible.builtin.include_tasks: 'setup_apt.yaml'

- name: 'Setup Packages.'
  ansible.builtin.include_tasks: 'setup_packages.yaml'

- name: 'Setup AppArmor.'
  ansible.builtin.include_tasks: 'setup_apparmor.yaml'

- name: 'Setup Grub.'
  ansible.builtin.include_tasks: 'setup_grub.yaml'

- name: 'Setup Kernel Modules.'
  ansible.builtin.include_tasks: 'setup_kernel_modules.yaml'

- name: 'Setup PCI Passthrough.'
  ansible.builtin.include_tasks: 'setup_pci_passthrough.yaml'

- name: 'Setup Kubernetes Support.'
  ansible.builtin.include_tasks: 'setup_kubernetes.yaml'

- name: 'Setup Miscellaneous Tweaks.'
  ansible.builtin.include_tasks: 'setup_tweaks.yaml'

- name: 'Setup Local Shares.'
  ansible.builtin.include_tasks: 'setup_local_shares.yaml'
