description: |-
    Dell R720XD Proxmox Server #3
prompt:
    colors:
        primary: 220
        secondary: 32
        tertiary: 58
    emoji: ☀️
pve_cluster_id: rain_house
pve_ip_address: 10.3.0.2
