---

# PCI IDs for passthrough.
spn_pci_ids: []

# Apt packages.
spn_apt_packages:
  - 'apt-file'
  - 'bc'
  - 'build-essential'
  - 'cargo'
  - 'curl'
  - 'ffmpeg'
  - 'git'
  - 'jq'
  - 'libacl1-dev'
  - 'libffi-dev'
  - 'libssl-dev'
  - 'mailutils'
  - 'nfs-client'
  - 'nfs-common'
  - 'python3'
  - 'python3-apt'
  - 'python3-dev'
  - 'python3-pip'
  - 'python3-setuptools'
  - 'python3-venv'
  - 'rsync'
  - 'sudo'
  - 'yadm'

# Pip packages.
spn_pip_packages:
  - 'ansible'
  - 'awscli'
  - 'bcrypt'
  - 'bdfr'
  - 'boto3'
  - 'docker'
  - 'kubernetes'
  - 'passlib'
  - 'proxmoxer'
  - 'requests'
  - 'torrent_parser'
  - 'typing_extensions'
  - 'virtualenv'

# Prefix to FS path mounted to hosts.
spn_local_share_prefix: null
# Hosts that exist on this Proxmox node (and can thus mount local shares).
spn_local_share_hosts: []

# All K8s masters.
spn_k8s_master_hostnames: []
# All K8s nodes.
spn_k8s_node_hostnames: []
# All K8s clusteres.
k8s_cluster_names: []
# Prefix to NFS path exported to k8s clusters.
k8s_nfs_prefix: null
