---

# PCI IDs for passthrough.
spn_pci_ids: []

# Apt packages.
spn_apt_packages:
  - 'apt-file'
  - 'bc'
  - 'build-essential'
  - 'cargo'
  - 'curl'
  - 'ffmpeg'
  - 'git'
  - 'jq'
  - 'libacl1-dev'
  - 'libffi-dev'
  - 'libssl-dev'
  - 'mailutils'
  - 'nfs-client'
  - 'nfs-common'
  - 'python3'
  - 'python3-apt'
  - 'python3-dev'
  - 'python3-pip'
  - 'python3-setuptools'
  - 'python3-venv'
  - 'rsync'
  - 'sudo'
  - 'yadm'

# Pip packages.
spn_pip_packages:
  - 'ansible'
  - 'awscli'
  - 'bcrypt'
  - 'bdfr'
  - 'boto3'
  - 'docker'
  - 'kubernetes'
  - 'passlib'
  - 'proxmoxer'
  - 'requests'
  - 'torrent_parser'
  - 'typing_extensions'
  - 'virtualenv'
