---
- name: 'Create S3 bucket.'
  amazon.aws.s3_bucket:
    aws_access_key: "{{ sh_aws_main_access_key }}"
    aws_secret_key: "{{ sh_aws_main_secret_key }}"
    region: "{{ sh_aws_region }}"
    name: "{{ sh_s3_bucket_name }}"
    state: 'present'
    versioning: no
