---
- name: 'AWS IAM user management.'
  delegate_to: 'localhost'
  block:

    - name: 'Create an AWS IAM user for this host.'
      community.aws.iam:
        aws_access_key: "{{ sh_aws_main_access_key }}"
        aws_secret_key: "{{ sh_aws_main_secret_key }}"
        region: "{{ sh_aws_region }}"
        iam_type: 'user'
        name: "{{ sh_aws_iam_host_user }}"
        state: 'present'
        password: "{{ sh_aws_iam_host_password }}"
        update_password: 'on_create'
        access_key_state: 'create'
        key_count: 0

    - name: 'Retrieve host data for this host.'
      block:

        - name: 'Lookup host data for this host.'
          ansible.builtin.set_fact:
            sh_host_data: "{{ lookup('amazon.aws.aws_ssm', sh_aws_iam_host_ssm_parameter_store_data_name, aws_access_key=sh_aws_main_access_key, aws_secret_key=sh_aws_main_secret_key) | from_json }}"

      rescue:

        - name: 'Set a safe default fact.'
          ansible.builtin.set_fact:
            sh_host_data: {}

    - name: 'Set facts for access key ID and secret access key.'
      ansible.builtin.set_fact:
        sh_access_key_id: "{{ sh_host_data.access_key_id | default('') }}"
        sh_secret_access_key: "{{ sh_host_data.secret_access_key | default('') }}"

    - name: 'Create a new access key ID and secret access key.'
      when: 'not sh_access_key_id or not sh_secret_access_key'
      block:

        - name: 'Create and retrieve access key.'
          ansible.builtin.command:
            cmd: "aws iam create-access-key --user-name {{ sh_aws_iam_host_user }}"
          environment:
            AWS_REGION: '{{ sh_aws_region }}'
            AWS_ACCESS_KEY_ID: '{{ sh_aws_main_access_key }}'
            AWS_SECRET_ACCESS_KEY: '{{ sh_aws_main_secret_key }}'
          register: 'sh_access_key_command'

        - name: 'Get access key ID and secret access key from command output.'
          ansible.builtin.set_fact:
            sh_access_key_output: "{{ sh_access_key_command.stdout | from_json }}"

        - name: 'Set new access key ID and secret access key.'
          ansible.builtin.set_fact:
            sh_new_access_key_id: "{{ sh_access_key_output.AccessKey.AccessKeyId }}"
            sh_new_secret_access_key: "{{ sh_access_key_output.AccessKey.SecretAccessKey }}"

        - name: 'Set new host data.'
          ansible.builtin.set_fact:
            sh_new_host_data:
              access_key_id: "{{ sh_new_access_key_id }}"
              secret_access_key: "{{ sh_new_secret_access_key }}"

        - name: 'Rebuild host data.'
          ansible.builtin.set_fact:
            sh_host_data: "{{ sh_host_data | default({}) | combine(sh_new_host_data) }}"

        - name: 'Update access key ID and secret access key.'
          community.aws.aws_ssm_parameter_store:
            name: "{{ sh_aws_iam_host_ssm_parameter_store_data_name }}"
            description: "Host data for {{ sh_hostname }}"
            string_type: 'SecureString'
            value: "{{ sh_host_data | to_nice_json }}"
