---
- name: 'Add the Plex apt signing key.'
  ansible.builtin.apt_key:
    url: 'https://downloads.plex.tv/plex-keys/PlexSign.key'
    state: 'present'

- name: 'Add APT repository for Plex.'
  ansible.builtin.apt_repository:
    repo: 'deb https://downloads.plex.tv/repo/deb public main'
    state: 'present'
  when: 'sh_host_uses_apt'

- name: 'Install Plex Media Server.'
  ansible.builtin.apt:
    name:
      - 'plexmediaserver'
    state: 'latest'
    update_cache: yes
  when: 'sh_host_uses_apt'
  notify: 'Restart Plex Media Server.'

- name: 'Force all notified handlers to run at this point.'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Start Plex Media Server.'
  ansible.builtin.service:
    name: 'plexmediaserver'
    state: 'started'
