---
- name: 'Set fact for directories to create and change ownership.'
  ansible.builtin.set_fact:
    sh_ubooquity_paths:
    - '/mnt/host/ubooquity'
    - '/mnt/host/ubooquity-files'
    - '/mnt/plunking'

- name: 'Change file permissions.'
  ansible.builtin.file:
    path: "{{ sh_filepath }}"
    owner: '1000'
    group: '1000'
    mode: '0755'
    state: 'directory'
  loop: "{{ sh_ubooquity_paths }}"
  loop_control:
    loop_var: 'sh_filepath'

- name: 'Set up Ubooquity.'
  community.docker.docker_container:
    name: 'ubooquity'
    image: 'lscr.io/linuxserver/ubooquity'
    state: 'started'
    restart: yes
    network_mode: 'host'
    volumes:
      - '/mnt/host/ubooquity:/config'
      - '/mnt/host/ubooquity-files:/files'
      - '/mnt/plunking:/plunking'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: 'America/New_York'
      MAXMEM: '8192'
    restart_policy: 'unless-stopped'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.ubooquity.rule: "HostRegexp(`ubooquity.{{ sh_personal_fqdn }}`, `{subdomain}.ubooquity.{{ sh_personal_fqdn }}`, `ubooquity.{{ sh_private_fqdn }}`, `{subdomain}.ubooquity.{{ sh_private_fqdn }}`)"
      traefik.http.routers.ubooquity.tls: 'true'
      traefik.http.routers.ubooquity.service: 'ubooquity'
      traefik.http.services.ubooquity.loadbalancer.server.port: '2202'
      traefik.http.services.ubooquity.loadbalancer.server.scheme: 'http'
      traefik.http.routers.ubooquity_admin.rule: "HostRegexp(`ubooquity-admin.{{ sh_personal_fqdn }}`, `{subdomain}.ubooquity-admin.{{ sh_personal_fqdn }}`, `ubooquity-admin.{{ sh_private_fqdn }}`, `{subdomain}.ubooquity-admin.{{ sh_private_fqdn }}`)"
      traefik.http.routers.ubooquity_admin.tls: 'true'
      traefik.http.routers.ubooquity_admin.service: 'ubooquity_admin'
      traefik.http.services.ubooquity_admin.loadbalancer.server.port: '2203'
      traefik.http.services.ubooquity_admin.loadbalancer.server.scheme: 'http'
    container_default_behavior: 'no_defaults'
