---
- name: 'Install npm.'
  ansible.builtin.apt:
    name: 'npm'

- name: 'Globally install podcast-dl.'
  community.general.npm:
    name: 'podcast-dl'
    global: yes

- name: 'Set up podcast-dl cron job.'
  become: yes
  become_user: "{{ sh_normal_user_name }}"
  ansible.builtin.cron:
    name: 'download-new-podcasts'
    special_time: 'weekly'
    job: |
      /bin/bash -lc 'pod_download_new /mnt/podcasts'

- name: 'Set up rsync cron job.'
  become: yes
  become_user: "{{ sh_normal_user_name }}"
  ansible.builtin.cron:
    name: 'sync-podcasts'
    special_time: 'daily'
    job: |
      /bin/bash -lc 'rsync --rsync-path=/volume1/@appstore/synocli-net/bin/rsync --archive --human-readable --verbose --whole-file /mnt/podcasts/* uller:/volume1/Podcasts/'
