---
- name: 'Set fact for directories to create and change ownership.'
  ansible.builtin.set_fact:
    sh_app_paths:
    - '/mnt/host/airsonic-data'
    - '/mnt/host/airsonic-playlists'
    - '/mnt/podcasts'

- name: 'Change file permissions.'
  ansible.builtin.file:
    path: "{{ sh_filepath }}"
    owner: '1000'
    group: '1000'
    mode: '0755'
    state: 'directory'
  loop: "{{ sh_app_paths }}"
  loop_control:
    loop_var: 'sh_filepath'

- name: 'Set up Airsonic.'
  community.docker.docker_container:
    name: 'airsonic'
    image: 'airsonic/airsonic'
    state: 'started'
    restart: yes
    network_mode: 'host'
    volumes:
      - '/mnt/host/airsonic-data:/airsonic/data'
      - '/mnt/host/airsonic-playlists:/airsonic/playlists'
      - '/mnt/podcasts:/airsonic/podcasts'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: 'America/New_York'
      MAXMEM: '8192'
    restart_policy: 'unless-stopped'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.airsonic.rule: "HostRegexp(`airsonic.{{ sh_personal_fqdn }}`, `{subdomain}.airsonic.{{ sh_personal_fqdn }}`, `airsonic.{{ sh_private_fqdn }}`, `{subdomain}.airsonic.{{ sh_private_fqdn }}`)"
      traefik.http.routers.airsonic.tls: 'true'
      traefik.http.routers.airsonic.service: 'airsonic'
      traefik.http.services.airsonic.loadbalancer.server.port: '4040'
      traefik.http.services.airsonic.loadbalancer.server.scheme: 'http'
    container_default_behavior: 'no_defaults'
