---
- name: 'Enable kernel modules.'
  ansible.builtin.copy:
    content: "{{ sh_module_name }}"
    dest: "/etc/modules-load.d/{{ sh_module_name }}.conf"
    mode: 0600
  loop:
    - 'aufs'
    - 'br_netfilter'
    - 'overlay'
    - 'vfio'
    - 'vfio_iommu_type1'
    - 'vfio_pci'
    - 'vfio_virqfd'
  loop_control:
    loop_var: 'sh_module_name'

- name: 'Blacklist certain kernel modules.'
  ansible.builtin.blockinfile:
    path: '/etc/modprobe.d/blacklist.conf'
    block: |
      blacklist radeon
      blacklist nouveau
      blacklist nvidia

- name: 'Modify some settings to prepare for Kubernetes.'
  ansible.builtin.copy:
    dest: '/etc/sysctl.d/sh_kubernetes.conf'
    content: |
      vm.swappiness=0
      net.ipv4.ip_forward=1
      net.netfilter.nf_conntrack_max=131072
    mode: 0600

- name: 'Run all sysctl updates.'
  ansible.builtin.command:
    cmd: 'sysctl --system'
  changed_when: no

- name: 'Disable swap if not already disabled.'
  ansible.builtin.command:
    cmd: 'swapoff -a'
  changed_when: no

- name: 'Redirect port 443 to port 8006 for the PVE admin interface.'
  ansible.builtin.shell:
    cmd: |
      /sbin/iptables -F
      /sbin/iptables -t nat -F
      /sbin/iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8006
  changed_when: no

- name: 'Modprobe kernel modules.'
  community.general.modprobe:
    name: "{{ sh_module_name }}"
  loop:
    - 'aufs'
    - 'br_netfilter'
    - 'overlay'
    - 'vfio'
    - 'vfio_iommu_type1'
    - 'vfio_pci'
    - 'vfio_virqfd'
  loop_control:
    loop_var: 'sh_module_name'

- name: 'Update system APT repositories.'
  ansible.builtin.apt_repository:
    repo: "{{ sh_repository_line }}"
  loop:
    - 'deb http://ftp.us.debian.org/debian bullseye main contrib'
    - 'deb http://ftp.us.debian.org/debian bullseye-updates main contrib'
    - 'deb http://ftp.us.debian.org/debian bullseye-backports main'
    - 'deb http://security.debian.org bullseye-security main contrib'
  loop_control:
    loop_var: 'sh_repository_line'

- name: 'Disable Enterprise Proxmox package repository configuration.'
  ansible.builtin.file:
    path: '/etc/apt/sources.list.d/pve-enterprise.list'
    state: 'absent'

- name: 'Remove the enterprise Proxmox package repository configuration.'
  ansible.builtin.apt_repository:
    repo: "{{ sh_repository_line }}"
    filename: 'pve-enterprise'
    state: 'absent'
  loop:
    - 'deb https://enterprise.proxmox.com/debian bullseye pve-enterprise'
    - 'deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise'
  loop_control:
    loop_var: 'sh_repository_line'

- name: 'Add the community Proxmox package repository configuration.'
  ansible.builtin.apt_repository:
    repo: 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
    filename: 'pve-community'

- name: 'Disable the subscription banner.'
  ansible.builtin.replace:
    path: '/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js'
    regexp: "data.status !== 'Active'"
    replace: 'false'

- name: 'Restart PVE Proxy.'
  ansible.builtin.systemd:
    name: 'pveproxy'
    state: 'restarted'

- name: 'Define the docker-default AppArmor profile.'
  ansible.builtin.copy:
    dest: '/etc/apparmor.d/docker-default'
    content: |
      #include <tunables/global>

      profile docker-default flags=(attach_disconnected,mediate_deleted) {

        #include <abstractions/base>

        ptrace peer=@{profile_name},

        network,
        capability,
        file,
        umount,

        deny @{PROC}/* w,  # deny write for all files directly in /proc (not in a subdir)
        # deny write to files not in /proc/<number>/** or /proc/sys/**
        deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
        deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
        deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
        deny @{PROC}/sysrq-trigger rwklx,
        deny @{PROC}/kcore rwklx,
        deny @{PROC}/mem rwklx,
        deny @{PROC}/kmem rwklx,

        deny mount,

        deny /sys/[^f]*/** wklx,
        deny /sys/f[^s]*/** wklx,
        deny /sys/fs/[^c]*/** wklx,
        deny /sys/fs/c[^g]*/** wklx,
        deny /sys/fs/cg[^r]*/** wklx,
        deny /sys/firmware/** rwklx,
        deny /sys/kernel/security/** rwklx,
      }
    mode: 0644

- name: 'Restart AppArmor.'
  ansible.builtin.systemd:
    name: 'pveproxy'
    state: 'restarted'
