---
- name: 'Create privately-resolvable DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    aws_access_key: "{{ sh_aws_main_access_key }}"
    aws_secret_key: "{{ sh_aws_main_secret_key }}"
    overwrite: yes
    hosted_zone_id: "{{ sh_route53_private_zone_id }}"
    state: 'present'
    type: 'A'
    record: "{{ sh_private_fqdn }}"
    value: "{{ sh_ipv4_address }}"

- name: 'Create privately-resolvable wildcard DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    aws_access_key: "{{ sh_aws_main_access_key }}"
    aws_secret_key: "{{ sh_aws_main_secret_key }}"
    alias: yes
    alias_hosted_zone_id: "{{ sh_route53_private_zone_id }}"
    overwrite: yes
    hosted_zone_id: "{{ sh_route53_private_zone_id }}"
    state: 'present'
    type: 'A'
    record: "*.{{ sh_private_fqdn }}"
    value: "{{ sh_private_fqdn }}"

- name: 'Create publicly-resolvable DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    aws_access_key: "{{ sh_aws_main_access_key }}"
    aws_secret_key: "{{ sh_aws_main_secret_key }}"
    alias: yes
    alias_hosted_zone_id: "{{ sh_route53_personal_zone_id }}"
    overwrite: yes
    hosted_zone_id: "{{ sh_route53_personal_zone_id }}"
    state: 'present'
    type: 'A'
    record: "{{ sh_personal_fqdn }}"
    value: "{{ sh_personal_domain_name }}"

- name: 'Create publicly-resolvable wildcard DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    aws_access_key: "{{ sh_aws_main_access_key }}"
    aws_secret_key: "{{ sh_aws_main_secret_key }}"
    alias: yes
    alias_hosted_zone_id: "{{ sh_route53_personal_zone_id }}"
    overwrite: yes
    hosted_zone_id: "{{ sh_route53_personal_zone_id }}"
    state: 'present'
    type: 'A'
    record: "*.{{ sh_personal_fqdn }}"
    value: "{{ sh_personal_fqdn }}"
