---
- name: 'Set up authorized keys'
  ansible.posix.authorized_key:
    user: "{{ sh_normal_user_name }}"
    state: 'present'
    key: "{{ sh_pubkey_item }}"
  become: yes
  become_user: "{{ sh_normal_user_name }}"
  loop: "{{ sh_admin_ssh_public_keys }}"
  loop_control:
    index_var: 'sh_pubkey_index'
    loop_var: 'sh_pubkey_item'

- name: 'Set up authorized keys (root)'
  ansible.posix.authorized_key:
    state: 'present'
    key: "{{ sh_pubkey_item }}"
  loop: "{{ sh_admin_ssh_public_keys }}"
  loop_control:
    index_var: 'sh_pubkey_index'
    loop_var: 'sh_pubkey_item'
