---
- name: 'Create the Traefik configuration directory.'
  ansible.builtin.file:
    path: '/mnt/host/traefik/conf.d/'
    state: 'directory'
    mode: '0600'

- name: 'Create the Traefik container.'
  community.general.docker_container:
    name: 'traefik'
    image: 'traefik:2.2'
    restart_policy: 'unless-stopped'
    recreate: yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "/mnt/host/traefik:/etc/traefik"
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: |
      --api.dashboard=false
      --serversTransport.insecureskipverify=true
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --providers.file=true
      --providers.file.directory='/etc/traefik/conf.d'
      --providers.file.watch=true
      --entryPoints.web
      --entryPoints.web.address=':80'
      --entryPoints.web.http
      --entryPoints.web.http.redirections
      --entryPoints.web.http.redirections.entryPoint
      --entryPoints.web.http.redirections.entryPoint.to='websecure'
      --entryPoints.web.http.redirections.entryPoint.scheme='https'
      --entryPoints.web.forwardedHeaders.insecure
      --entryPoints.websecure
      --entryPoints.websecure.address=':443'
      --certificatesResolvers.{{ sh_letsencrypt_private_domain_resolver_name }}.acme.email="{{ sh_letsencrypt_email }}"
      --certificatesResolvers.{{ sh_letsencrypt_private_domain_resolver_name }}.acme.storage='/etc/traefik/letsencrypt.json'
      --certificatesResolvers.{{ sh_letsencrypt_private_domain_resolver_name }}.acme.dnsChallenge
      --certificatesResolvers.{{ sh_letsencrypt_private_domain_resolver_name }}.acme.dnsChallenge.provider='route53'
    env:
      AWS_ACCESS_KEY_ID: "{{ sh_aws_main_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ sh_aws_main_secret_key }}"
    container_default_behavior: 'no_defaults'
