---
- name: 'Create NFS automount custom service.'
  ansible.builtin.copy:
    dest: "/etc/systemd/system/mnt-youtube.mount"
    content: |
      [Unit]
      Description=Mount YouTube NFS Share

      [Mount]
      What={{ sh_nfs_server }}:{{ sh_nfs_youtube_path }}
      Where=/mnt/youtube
      Type=nfs
      Options=defaults
      TimeoutSec=10

      [Install]
      WantedBy=multi-user.target
      WantedBy=docker.target
    mode: 0644
    owner: 'root'
    group: 'root'

- name: 'Start NFS automount custom service.'
  ansible.builtin.systemd:
    name: 'mnt-youtube.mount'
    daemon_reload: yes
    state: 'started'
    enabled: yes

- name: 'Set fact for MariaDB password path.'
  ansible.builtin.set_fact:
    sh_tubesync_mariadb_password_path: '/mnt/host/mariadb_password'

- name: 'Attempt to retrieve remote password.'
  block:

    - name: 'Read remote password.'
      ansible.builtin.slurp:
        src: "{{ sh_tubesync_mariadb_password_path }}"
      register: 'sh_tubesync_mariadb_password_slurp'

    - name: 'Set fact for remote password.'
      ansible.builtin.set_fact:
        sh_tubesync_mariadb_password: "{{ sh_tubesync_mariadb_password_slurp['content'] | b64decode }}"

  rescue:

    - name: 'Generate MariaDB password.'
      ansible.builtin.set_fact:
        sh_tubesync_mariadb_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

- name: 'Set remote password.'
  ansible.builtin.copy:
    content: "{{ sh_tubesync_mariadb_password }}"
    dest: "{{ sh_tubesync_mariadb_password_path }}"

- name: 'Set up MariaDB.'
  community.docker.docker_container:
    name: 'mariadb'
    image: 'mariadb:10'
    state: 'started'
    restart: yes
    network_mode: 'host'
    restart_policy: 'unless-stopped'
    volumes:
      - '/mnt/host/mariadb:/var/lib/mysql'
    env:
      MARIADB_DATABASE: 'tubesync'
      MARIADB_USER: 'tubesync'
      MARIADB_PASSWORD: "{{ sh_tubesync_mariadb_password }}"
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
    container_default_behavior: 'no_defaults'

- name: 'Set up TubeSync.'
  community.docker.docker_container:
    name: 'tubesync'
    image: 'ghcr.io/meeb/tubesync:latest'
    state: 'started'
    restart: yes
    network_mode: 'host'
    restart_policy: 'unless-stopped'
    volumes:
      - '/mnt/host/tubesync:/config'
      - '/mnt/youtube:/downloads'
      - '/mnt/host/tubesync/local_settings.py:/app/tubesync/local_settings.py'
    env:
      TZ: 'America/New_York'
      PUID: '998'
      PGID: '998'
      DATABASE_CONNECTION: "mysql://tubesync:{{ sh_tubesync_mariadb_password }}@127.0.0.1:3306/tubesync"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.tubesync.rule: "HostRegexp(`tubesync.{{ sh_personal_fqdn }}`, `{subdomain}.tubesync.{{ sh_personal_fqdn }}`, `tubesync.{{ sh_private_fqdn }}`, `{subdomain}.tubesync.{{ sh_private_fqdn }}`)"
      traefik.http.routers.tubesync.tls: 'true'
      traefik.http.routers.tubesync.service: 'tubesync'
      traefik.http.services.tubesync.loadbalancer.server.port: '4848'
      traefik.http.services.tubesync.loadbalancer.server.scheme: 'http'
    container_default_behavior: 'no_defaults'


