---
- name: 'Install yt-dlp.'
  ansible.builtin.pip:
    name: 'yt-dlp'

- name: 'Set up YouTube cron job.'
  become: yes
  become_user: "{{ sh_normal_user_name }}"
  ansible.builtin.cron:
    name: 'download-new-videos'
    special_time: 'weekly'
    job: |
      /bin/bash -lc 'yt_download_new /mnt/youtube'

- name: 'Set up rsync cron job.'
  become: yes
  become_user: "{{ sh_normal_user_name }}"
  ansible.builtin.cron:
    name: 'sync-videos'
    special_time: 'daily'
    job: |
      /bin/bash -lc 'rsync --rsync-path=/volume1/@appstore/synocli-net/bin/rsync --archive --human-readable --verbose --whole-file /mnt/youtube/* uller:/volume1/Video/YouTube/'

- name: 'Set up Alltube.'
  community.docker.docker_container:
    name: 'alltube'
    image: 'rudloff/alltube'
    state: 'started'
    restart: yes
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart_policy: 'unless-stopped'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.alltube.rule: "HostRegexp(`alltube.{{ sh_personal_fqdn }}`, `{subdomain:[a-z0-9-]+}.alltube.{{ sh_personal_fqdn }}`, `alltube.{{ sh_private_fqdn }}`, `{subdomain:[a-z0-9-]+}.alltube.{{ sh_private_fqdn }}`)"
      traefik.http.routers.alltube.tls: 'true'
      traefik.http.routers.alltube.tls.certresolver: "{{ sh_letsencrypt_private_domain_resolver_name }}"
      traefik.http.routers.alltube.tls.domains[0].main: "alltube.{{ sh_personal_fqdn }}"
      traefik.http.routers.alltube.tls.domains[0].sans: "*.alltube.{{ sh_personal_fqdn }}"
      traefik.http.routers.alltube.tls.domains[1].main: "alltube.{{ sh_private_fqdn }}"
      traefik.http.routers.alltube.tls.domains[1].sans: "*.alltube.{{ sh_private_fqdn }}"
      traefik.http.routers.alltube.service: 'alltube'
      traefik.http.services.alltube.loadbalancer.server.port: '80'
      traefik.http.services.alltube.loadbalancer.server.scheme: 'http'
    container_default_behavior: 'no_defaults'

