# This should always be 'python3' because it's 2021.
ansible_python_interpreter: 'python3'

# An SSH public key that I inject into newly created hosts for admin purposes.
admin_ssh_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQ57vLQqOxs70+02+u6bxjK6nbq0IS6aeFcQQ6lADrq4P+xgMT0H0aPnGk+thZTPmy5RZezzMd8yWzYTVku9qPyqsEiMmZGrHNMMDAacCmB5F8PcQBgwOCA8HNgGll0vTLhYq1ARHAX2vtw6DROX6isLHmeKz0zN8FRai2hgr88wWClhRd68yDldF7UoHNj0LkpsUNpJcq/Tq7da9rXFopP0wCaQ6r+aqnQTBi8KIbS8zRU3pCZ4Vi2OoZ+Fez56ya5XhvS3OIw2awyobFmzfuWvy1gM+b9f6Ksf2skF7D7bmhsn/19K/PHE+Rb/kx3QOA3IwPpd7oCIwdsNVe7lRJX5Ubx5jXmfc/aFVTk/bF0CSyh8ycSoWElMvI81UGMuToY/hPezz/sFUxShGxX7qiVLh1qQH9iJVLk7ZS50nwKaCr8Bn5Fyf0mcsX5E1+NtBxbiyQb5161CaixhwHKDceVCDhEggTO1IyTfNTvYG3nf0VbiTnPNun4v5PH120IKRnqdjUiONe0L4zdreQKskgg7uZPgh5VAb5c6kBgtIH4IsYo6BVJ5YFj2NqZHX5W4kbLV2eYmLruL9jPA+eMpwHX7omqZgkGsPyRztpATyvgUZjnsCG0tGdczLmOX+d9PyLP1A4ha6AgmGKTYlr+MA7LB/pr2hB6zueCSuD3zeRfw== nathan@fossoway'

# A clean, consistent version of the hostname.
hostname: "{{ inventory_hostname | splitext | first | lower }}"

# By default, use Ubuntu 21.04 as our template.
pve_template: 'ubuntu-21.04-standard_21.04-1_amd64.tar.gz'
