---
- name: 'Set the MOTD.'
  ansible.builtin.get_url:
    url: "{{ dot_motd_base_url }}/{{ dot_hostname }}.txt"
    dest: '/etc/motd'
    force: no
    owner: 'root'
    mode: 0644
  ignore_errors: yes
  become: yes

