---
- name: 'Set up AWS services.'
  delegate_to: 'localhost'
  block:

    - name: 'Set up IAM.'
      ansible.builtin.include_tasks: 'setup_iam.yaml'

    - name: 'Set up Route 53.'
      ansible.builtin.include_tasks: 'setup_route53.yaml'

