---
- name: 'Set up Route 53 records.'
  delegate_to: 'localhost'
  block:

    - name: 'Create privately-resolvable DNS records for the host.'
      delegate_to: 'localhost'
      community.aws.route53:
        aws_access_key: "{{ aws_default_access_key_id }}"
        aws_secret_key: "{{ aws_default_secret_access_key }}"
        overwrite: yes
        hosted_zone_id: "{{ route53_private_zone_id }}"
        state: 'present'
        type: 'A'
        record: "{{ host_private_fqdn }}"
        value: "{{ ipv4_address }}"

    - name: 'Create privately-resolvable wildcard DNS records for the host.'
      delegate_to: 'localhost'
      community.aws.route53:
        aws_access_key: "{{ aws_default_access_key_id }}"
        aws_secret_key: "{{ aws_default_secret_access_key }}"
        alias: yes
        alias_hosted_zone_id: "{{ route53_private_zone_id }}"
        overwrite: yes
        hosted_zone_id: "{{ route53_private_zone_id }}"
        state: 'present'
        type: 'A'
        record: "*.{{ host_private_fqdn }}"
        value: "{{ host_private_fqdn }}"

    - name: 'Create publicly-resolvable DNS records for the host.'
      delegate_to: 'localhost'
      community.aws.route53:
        aws_access_key: "{{ aws_default_access_key_id }}"
        aws_secret_key: "{{ aws_default_secret_access_key }}"
        alias: yes
        alias_hosted_zone_id: "{{ route53_personal_zone_id }}"
        overwrite: yes
        hosted_zone_id: "{{ route53_personal_zone_id }}"
        state: 'present'
        type: 'A'
        record: "{{ host_personal_fqdn }}"
        value: "{{ personal_domain_name }}"

    - name: 'Create publicly-resolvable wildcard DNS records for the host.'
      delegate_to: 'localhost'
      community.aws.route53:
        aws_access_key: "{{ aws_default_access_key_id }}"
        aws_secret_key: "{{ aws_default_secret_access_key }}"
        alias: yes
        alias_hosted_zone_id: "{{ route53_personal_zone_id }}"
        overwrite: yes
        hosted_zone_id: "{{ route53_personal_zone_id }}"
        state: 'present'
        type: 'A'
        record: "*.{{ host_personal_fqdn }}"
        value: "{{ host_personal_fqdn }}"
