---
- name: 'Set up Docker.'
  remote_user: 'root'
  block:

    - name: 'Install Docker.'
      ansible.builtin.include_role:
        name: 'geerlingguy.docker'
      vars:
        docker_edition: 'ce'
        docker_package: "docker-{{ docker_edition }}"
        docker_package_state: 'present'
        docker_service_state: 'started'
        docker_service_enabled: yes
        docker_restart_handler_state: 'restarted'
        docker_install_compose: yes
        docker_users:
          - "{{ dck_normal_user_name }}"
        docker_daemon_options:
          exec-opts:
            - 'native.cgroupdriver=systemd'

    - name: 'Log in to Docker Hub.'
      community.docker.docker_login:
        username: "{{ dck_docker_hub_username }}"
        password: "{{ dck_docker_hub_password }}"
      when: 'dck_docker_hub_login is true'
