---
- name: 'Reset and reinitialize the cluster.'
  remote_user: 'root'
  block:

    - name: 'Run setup for this host.'
      ansible.builtin.setup:

    - name: 'Add all hosts to a set of universal groups.'
      ansible.builtin.group_by:
        key: "{{ k8s_cluster_group }}"
      loop: "{{ k8s_universal_cluster_groups }}"
      loop_control:
        index_var: 'k8s_index'
        loop_var: 'k8s_cluster_group'

    - name: 'Redeploy cluster group tasks.'
      when: 'k8s_role == "master"'
      block:

        - name: 'Execute cluster group tasks.'
          ansible.builtin.include_tasks: "tasks/cluster_groups/{{ k8s_cluster_group }}.yaml"
          when: 'k8s_cluster_group in group_names'
          loop: "{{ k8s_cluster_groups }}"
          loop_control:
            index_var: 'k8s_index'
            loop_var: 'k8s_cluster_group'

