---
- name: 'Setup Plex.'
  remote_user: 'root'
  block:

    - name: 'Set up NFS.'
      ansible.builtin.include_tasks: 'setup_nfs.yaml'

    - name: 'Set up Plex.'
      ansible.builtin.include_tasks: 'setup_plex.yaml'
