---
- name: 'Set up Code-Server.'
  remote_user: 'root'
  block:

    - name: 'Setup Plex Media Server.'
      community.docker.docker_container:
        name: 'plex'
        image: 'linuxserver/plex:latest'
        restart_policy: 'unless-stopped'
        recreate: yes
        network_mode: 'host'
        labels:
          traefik.enable: 'true'
          traefik.http.routers.plex.rule: "HostRegexp(`plex.{{ host_private_fqdn }}`, `{subdomain:[a-z0-9-]+}.plex.{{ host_private_fqdn }}`)"
          traefik.http.routers.plex.tls: 'true'
          traefik.http.routers.plex.tls.certresolver: "{{ letsencrypt_private_domain_resolver }}"
          traefik.http.routers.plex.tls.domains[0].main: "plex.{{ host_private_fqdn }}"
          traefik.http.routers.plex.tls.domains[0].sans: "*.plex.{{ host_private_fqdn }}"
          traefik.http.routers.plex.service: 'plex'
          traefik.http.services.plex.loadbalancer.server.port: '32400'
          traefik.http.services.plex.loadbalancer.server.scheme: 'http'
        env:
          PUID: "{{ normal_user_uid }}"
          PGID: "{{ normal_user_gid }}"
          UMASK: '0000'
          TZ: "{{ local_timezone }}"
        volumes:
          - "{{ plex_media_server_directory }}:/config"
          - '/Movies:/Movies'
          - '/Music:/Music'
          - '/Podcasts:/Podcasts'
          - '/TV:/TV'
          - '/YouTube:/YouTube'

    - name: 'Create the scanners/series directory.'
      ansible.builtin.file:
        path: "{{ plex_media_server_directory }}/Scanners/Series"
        state: 'directory'
        mode: '0755'
        owner: "{{ normal_user_name }}"
        group: "{{ normal_user_group }}"

    - name: 'Install Absolute Series Scanner.'
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py'
        dest: "{{ plex_media_server_directory }}/Scanners/Series/Absolute Series Scanner.py"
        owner: "{{ normal_user_name }}"
        group: "{{ normal_user_group }}"

    - name: 'Install YouTube Agent.'
      ansible.builtin.git:
        repo: 'https://github.com/ZeroQI/YouTube-Agent.bundle.git'
        dest: "{{ plex_media_server_directory }}/Plug-ins/YouTube-Agent.bundle"
        update: no
      become: yes
      become_user: "{{ normal_user_name }}"

    - name: 'Install YouTube-DL Agent.'
      ansible.builtin.git:
        repo: 'https://github.com/JordyAlkema/Youtube-DL-Agent.bundle.git'
        dest: "{{ plex_media_server_directory }}/Plug-ins/Youtube-DL-Agent.bundle"
        update: no
      become: yes
      become_user: "{{ normal_user_name }}"
