---
# The hostname of this host.
k8s_hostname: "{{ inventory_hostname | splitext | first | lower }}"

# The cluster name, e.g. "my-happy-cluster".  Set in inventory.
k8s_cluster: null
# The cluster role ('master' or 'node').  Set in inventory.
k8s_role: null
# All K8s hosts, regardless of role or cluster.
k8s_hosts: []
# All K8s masters, regardless of cluster.
k8s_master_hosts: []
# All K8s nodes, regardless of cluster.
k8s_node_hosts: []
# All K8s hosts in this cluster.
k8s_cluster_hosts: []

# The IP address of this host.
k8s_ipv4_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

# Account ID, access key, etc used to create policies, users, Route 53 records, etc.
k8s_aws_region: 'us-east-1'
k8s_aws_account_id: null
k8s_aws_main_access_key: null
k8s_aws_main_secret_key: null

# Name and password of IAM user for cluster.
k8s_aws_iam_cluster_user: null
k8s_aws_iam_cluster_password: null

# Pattern for which SSM parameters this cluster is permitted to access.
k8s_aws_ssm_policy_pattern: "{{ ndk8s_aws_iam_cluster_user }}.*"

# Prefix of SSM parameter store data for cluster.
k8s_aws_iam_cluster_ssm_parameter_store_data_prefix: null

# Name of SSM parameter store data for cluster.
k8s_aws_iam_cluster_ssm_parameter_store_data_name: "{{ k8s_aws_iam_cluster_ssm_parameter_store_data_prefix }}{{ k8s_cluster }}.cluster_data"

# A Route 53 "private" zone ID.
k8s_route53_private_zone_id: null
# A Route 53 "personal" zone ID.
k8s_route53_personal_zone_id: null

# A private domain name.
k8s_private_domain_name: 'example.net'
# A personal domain name.
k8s_personal_domain_name: 'example.com'

# A "private" FQDN.
k8s_private_fqdn: "{{ k8s_cluster }}.{{ k8s_private_domain_name }}"
# A "personal" FQDN.
k8s_personal_fqdn: "{{ k8s_cluster }}.{{ k8s_personal_domain_name }}"

# Prefix to NFS path exported to k8s clusters.
k8s_nfs_prefix: null

# Cluster groups are special groups that have a defined setup task.
k8s_cluster_groups:
  - 'get_config'                  # Get Kubectl config.
  - 'route53'                     # Add DNS records.
  - 'helm'                        # Install Helm for package control.
  - 'metrics_server'              # Local metrics gathering and reporting.
  - 'nfs_provisioner'             # Allow provisioning persistent network storage.
  - 'local_storage_provisioner'   # Allow provisioning persistent local storage.
  - 'cert_manager'                # Permit TLS cert generation.
  - 'traefik'                     # Install and setup Traefik as Ingress Controller.
  - 'argocd'                      # Install ArgoCD as GitOps controller.
  - 'whoami'                      # Install Whoami as test service.
  - 'prometheus'                  # Install Kube-Prometheus-Stack for monitoring and reporting.
  - 'aws_iam_user'                # Create an AWS IAM user for the cluster.
  - 'aws_s3_bucket'               # Create an S3 bucket for the cluster.
  - 'aws_iam_policy'              # Allow retrieval of secrets from AWS SSM Parameter Store.
  - 'external_secrets'            # Allow secrets to persist past cluster lifetimes.

# Some cluster groups contain all hosts.
k8s_universal_cluster_groups:
  - 'get_config'
  - 'route53'
  - 'helm'
  - 'metrics_server'
  - 'nfs_provisioner'
  - 'local_storage_provisioner'
  - 'cert_manager'
  - 'traefik'
  - 'argocd'
  - 'whoami'
  - 'prometheus'
  - 'aws_iam_user'
  - 'aws_s3_bucket'
  - 'aws_iam_policy'
  - 'external_secrets'

# The hostname of the K8s NFS server.
k8s_nfs_server: null

# An easy password for accessing some services.
k8s_easy_password: null

# S3 bucket for this cluster.
k8s_s3_bucket_name: "clusters.{{ k8s_hostname }}"
