---
- name: 'Create the Traefik configuration directory.'
  ansible.builtin.file:
    path: "{{ traefik_data_dir }}/conf.d/"
    state: 'directory'
    mode: '0600'
    owner: 'root'
    group: 'root'
  become: yes

- name: 'Create the Traefik network.'
  community.docker.docker_network:
    name: 'traefik'

- name: 'Create the Traefik container.'
  community.general.docker_container:
    name: 'traefik'
    image: 'traefik:2.6'
    restart_policy: 'unless-stopped'
    recreate: yes
    network_mode: 'host'
    volumes:
      - '{{ traefik_data_dir }}:/etc/traefik'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: |
      --log.level=WARN
      --api.dashboard=false
      --serversTransport.insecureskipverify=true
      --providers.docker=true
      --providers.docker.watch=true
      --providers.docker.exposedByDefault=false
      --providers.file=true
      --providers.file.directory='/etc/traefik/conf.d'
      --providers.file.watch=true
      --entryPoints.web
      --entryPoints.web.address=':5080'
      --entryPoints.web.http
      --entryPoints.web.http.redirections
      --entryPoints.web.http.redirections.entryPoint
      --entryPoints.web.http.redirections.entryPoint.to='websecure'
      --entryPoints.web.http.redirections.entryPoint.scheme='https'
      --entryPoints.web.forwardedHeaders.insecure
      --entryPoints.websecure
      --entryPoints.websecure.address=':5443'
      --entryPoints.websecure.http.tls.certResolver={{ letsencrypt_private_domain_resolver }}
      --certificatesResolvers.{{ letsencrypt_private_domain_resolver }}.acme.email="{{ letsencrypt_email_address }}"
      --certificatesResolvers.{{ letsencrypt_private_domain_resolver }}.acme.storage='/etc/traefik/letsencrypt.json'
      --certificatesResolvers.{{ letsencrypt_private_domain_resolver }}.acme.dnsChallenge
      --certificatesResolvers.{{ letsencrypt_private_domain_resolver }}.acme.dnsChallenge.provider='route53'
    env:
      aws_default_access_key_id: "{{ route53_access_key_id }}"
      aws_default_secret_access_key: "{{ route53_secret_access_key }}"
    container_default_behavior: 'no_defaults'

- name: 'Create privately-resolvable Route 53 records for the host.'
  community.aws.route53:
    overwrite: yes
    aws_access_key: "{{ route53_access_key_id }}"
    aws_secret_key: "{{ route53_secret_access_key }}"
    hosted_zone_id: "{{ route53_private_zone_id }}"
    state: 'present'
    type: 'A'
    record: "{{ host_private_fqdn }}"
    value: "{{ ipv4_address }}"

- name: 'Create privately-resolvable Route 53 wildcard records for the host.'
  community.aws.route53:
    overwrite: yes
    aws_access_key: "{{ route53_access_key_id }}"
    aws_secret_key: "{{ route53_secret_access_key }}"
    hosted_zone_id: "{{ route53_private_zone_id }}"
    state: 'present'
    type: 'A'
    record: "*.{{ host_private_fqdn }}"
    value: "{{ ipv4_address }}"
