---
- name: 'Setup .gitconfig'
  community.general.git_config:
    scope: 'global'
    name: "{{ sh_gitconfig_item.key }}"
    value: "{{ sh_gitconfig_item.value }}"
  loop: "{{ sh_gitconfig | dict2items }}"
  loop_control:
    index_var: 'sh_index'
    loop_var: 'sh_gitconfig_item'
  changed_when: no
