---
- name: 'Create an SSH key if one does not already exist.'
  community.crypto.openssh_keypair:
    path: "{{ sh_ssh_private_key_path }}"
    comment: "{{ sh_user_at_hostname }}"
    owner: "{{ sh_user }}"
    group: "{{ sh_group }}"
    mode: '0600'
    regenerate: 'full_idempotence'
    size: 4096
    type: 'rsa'
