---
- name: 'Allow release-info to change for APT repositories.'
  ansible.builtin.command: 'apt-get update -y --allow-releaseinfo-change'
  args:
    warn: no
  when: 'sh_host_uses_apt'
  changed_when: no

- name: 'Install Apt packages.'
  ansible.builtin.apt:
    name:
      - 'apt-file'
      - 'bc'
      - 'build-essential'
      - 'cargo'
      - 'curl'
      - 'ffmpeg'
      - 'git'
      - 'jq'
      - 'libacl1-dev'
      - 'libffi-dev'
      - 'libssl-dev'
      - 'mailutils'
      - 'nfs-client'
      - 'nfs-common'
      - 'python3'
      - 'python3-apt'
      - 'python3-dev'
      - 'python3-pip'
      - 'python3-setuptools'
      - 'python3-venv'
      - 'rsync'
      - 'sudo'
      - 'yadm'
    cache_valid_time: "{{ 3600 * 24 }}"
  when: 'sh_host_uses_apt'

- name: 'Install Homebrew packages.'
  community.general.homebrew:
    name:
      - 'argocd'
      - 'bat'
      - 'coreutils'
      - 'findutils'
      - 'ffmpeg'
      - 'fzf'
      - 'gawk'
      - 'gnu-indent'
      - 'gnu-sed'
      - 'gnutls'
      - 'grep'
      - 'gnu-tar'
      - 'helm'
      - 'jc'
      - 'jq'
      - 'parallel'
      - "python@{{ sh_package_versions.python }}"
      - 'yadm'
      - 'yq'
    update_homebrew: no
  when: 'sh_host_uses_homebrew'

- name: 'Make sure pip is at the latest version.'
  ansible.builtin.pip:
    name: 'pip'
    state: 'forcereinstall'
  changed_when: no
  when: 'sh_reinstall_pip'

- name: 'Install Pip packages.'
  ansible.builtin.pip:
    name:
      - 'ansible'
      - 'awscli'
      - 'bcrypt'
      - 'bdfr'
      - 'boto3'
      - 'docker'
      - 'kubernetes'
      - 'passlib'
      - 'proxmoxer'
      - 'requests'
      - 'torrent_parser'
      - 'virtualenv'
    extra_args: '--ignore-installed'

- name: 'Set a fact to indicate that we have installed these packages.'
  ansible.builtin.set_fact:
    sh_common_packages_installed: yes
