---
- name: 'Add all hosts to a set of universal groups.'
  ansible.builtin.group_by:
    key: "{{ sh_setup_group }}"
  loop: "{{ sh_universal_setup_groups }}"
  loop_control:
    index_var: 'sh_index'
    loop_var: 'sh_setup_group'

- name: 'Add host to the traefik_local_proxy group unless it is in traefik_site_proxy.'
  ansible.builtin.group_by:
    key: 'traefik_local_proxy'
  when: '"traefik_site_proxy" not in group_names'
