---
- name: 'Set user and group facts.'
  ansible.builtin.include_tasks: 'set_user_facts.yaml'

- name: 'Set OS and distribution facts.'
  ansible.builtin.include_tasks: 'set_os_facts.yaml'

- name: 'Set host facts.'
  ansible.builtin.include_tasks: 'set_host_facts.yaml'

- name: 'Install some universally useful packages.'
  ansible.builtin.include_tasks: 'install_common_packages.yaml'
  when: 'sh_install_common_packages is true and sh_common_packages_installed is not defined'

- name: 'Create a normal user account.'
  ansible.builtin.include_tasks: 'create_normal_user.yaml'
  when: 'sh_create_normal_user is true and sh_normal_user_name is defined'

- name: 'Set the hostname explicitly.'
  ansible.builtin.include_tasks: 'set_hostname.yaml'
  when: 'sh_set_hostname is true and not sh_host_is_mac and not sh_host_is_synology'

- name: 'Enable passwordless sudo.'
  ansible.builtin.include_tasks: 'enable_passwordless_sudo.yaml'
  when: 'sh_enable_passwordless_sudo is true and sh_normal_user_name is defined'

- name: 'Create an SSH key.'
  ansible.builtin.include_tasks: 'create_ssh_key.yaml'

- name: 'Set setup groups.'
  ansible.builtin.include_tasks: 'set_setup_groups.yaml'

- name: 'Configure Git.'
  ansible.builtin.include_tasks: 'configure_git.yaml'
